#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
	/config/www/akaunting

# install app
if [ ! -f /config/www/akaunting/index.php ]; then
	echo "**** Downloading Akaunting ${VERSION} ****"
	curl -o \
		/tmp/akaunting.zip -L \
		"https://github.com/akaunting/akaunting/releases/download/${VERSION}/Akaunting_${VERSION}-Stable.zip"
	echo "**** Inflating akaunting.zip ****"
	unzip -q -o /tmp/akaunting.zip -d \
		/config/www/akaunting
	chown abc:abc -R \
		/config/www/akaunting
	rm \
		/tmp/akaunting.zip
fi
